### ISSUE TITLE
Hangman title has an unnecessary cursor

### ISSUE THREAD

**Issue by LaLiLuLeLoPS** [Rishi-Sharma2002/Hangman-React#3]
The title in the hangman game gets an unnecessary cursor. If you assign the issue to me I can remove it

**Comment by Acephoeni-X** [comment]
Assigned

**Comment by LaLiLuLeLoPS** [comment]
Could you also add the hacktober 2022 fest tag? Would be much appreciated

**Comment by LaLiLuLeLoPS** [comment]
Sorry please ignore, this is a local system issue

**Comment by Acephoeni-X** [comment]
Not an issue
